# Templated from `https://github.com/google-github-actions/setup-gcloud/blob/master/example-workflows/gke/deployment.yml`

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gke-test
    spec:
      containers:
      - name: gke-test
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
